problem:
  n: 21
  bound: bound3

model:
  _target_: combo_dl.models.mlp.MLP
  n: ${problem.n}
  hidden_layer_sizes: [64, 32, 16, 8, 4]
  output_size: 2
  dropout_probability: 0.1
  layernorm: true
  activation_function: "relu"

training:
  iterations: 50000
  batch_size: 4096
  learning_rate: 0.0001
  elite_proportion: 0.15
  early_stopping_patience: 2000
  survivor_proportion: 0.05
  checkpoint_frequency: 100
  save_best_constructions: true
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    mode: "max"
    factor: 0.5
    patience: 300
    min_lr: 0.000001

torch_compile: true
experiment_name: laplacian_bound3

defaults:
  - hydra
  - _self_

logging:
  wandb_mode: "online"
  checkpoint_dir: "runs"
