graph:
  _target_: combo_dl.strongly_regular_graphs_problem.StronglyRegularGraphs
  n: 13
  k: 6
  lambda_param: 2
  mu: 3

model:
  _target_: combo_dl.models.mlp.MLP
  n: ${graph.n}
  hidden_layer_sizes: [64, 32, 16, 8, 4]
  output_size: 2
  dropout_probability: 0.1
  layernorm: true
  activation_function: "relu"

training:
  iterations: 10000
  batch_size: 2048
  learning_rate: 0.001
  elite_proportion: 0.1
  early_stopping_patience: 600
  survivor_proportion: 0.02

# Inherit base configuration from hydra.yaml
defaults:
  - hydra
  - _self_

experiment_name: null  # Set to a string to name the WandB run and output directory
torch_compile: False

# Override specific logging settings if needed
logging:
  wandb_mode: "online"
  checkpoint_dir: "runs"